// <auto-generated />
using System;
using HRM.SantaLucia.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRM.SantaLucia.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260501225353_FixEmpleadoMonetaryColumnTypes")]
    partial class FixEmpleadoMonetaryColumnTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRM.SantaLucia.Web.Models.Entities.Asistencia", b =>
                {
                    b.Property<int>("AsistenciaKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsistenciaKey"));

                    b.Property<int>("EmpleadoKey")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("FechaKey")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("GoceSalario")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("HoraEntrada")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HoraSalida")
                        .HasColumnType("time");

                    b.Property<decimal>("HorasTrabajadas")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Justificacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MinutosTarde")
                        .HasColumnType("int");

                    b.Property<string>("MotivoPermiso")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AsistenciaKey");

                    b.HasIndex("EmpleadoKey", "FechaKey")
                        .IsUnique();

                    b.ToTable("Asistencia", "FACT");
                });

            modelBuilder.Entity("HRM.SantaLucia.Web.Models.Entities.Banco", b =>
                {
                    b.Property<int>("BancoKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BancoKey"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoBanco")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreBanco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BancoKey");

                    b.ToTable("Banco", "DIM");
                });

            modelBuilder.Entity("HRM.SantaLucia.Web.Models.Entities.Departamento", b =>
                {
                    b.Property<int>("DepartamentoKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartamentoKey"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("DepartamentoPadreKey")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("JefeKey")
                        .HasColumnType("int");

                    b.Property<string>("NombreDepartamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DepartamentoKey");

                    b.HasIndex("DepartamentoPadreKey");

                    b.HasIndex("JefeKey");

                    b.ToTable("Departamento", "DIM");
                });

            modelBuilder.Entity("HRM.SantaLucia.Web.Models.Entities.Empleado", b =>
                {
                    b.Property<int>("EmpleadoKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpleadoKey"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Apellido2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("BancoKey")
                        .HasColumnType("int");

                    b.Property<decimal?>("Bonos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CCSS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Canton")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContactoEmergencia")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CuentaBancaria")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("DepartamentoKey")
                        .HasColumnType("int");

                    b.Property<string>("DireccionExacta")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Distrito")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Edad")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("(DATEDIFF(YEAR, [FechaNacimiento], GETDATE()) - CASE WHEN DATEADD(YEAR, DATEDIFF(YEAR, [FechaNacimiento], GETDATE()), [FechaNacimiento]) > GETDATE() THEN 1 ELSE 0 END)", true);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmailPersonal")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmpleadoID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EstadoCivil")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaSalida")
                        .HasColumnType("datetime2");

                    b.Property<string>("Foto")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("JUPEMA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Magisterio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NivelEducativo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreCompleto")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComputedColumnSql("[Nombre] + ' ' + [Apellido1] + ' ' + ISNULL([Apellido2], '')", true);

                    b.Property<decimal?>("PorcentajeBP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PuestoKey")
                        .HasColumnType("int");

                    b.Property<decimal?>("Rebajos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SalarioBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SalarioNeto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sede")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TelefonoEmergencia")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoContrato")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EmpleadoKey");

                    b.HasIndex("BancoKey");

                    b.HasIndex("DepartamentoKey");

                    b.HasIndex("PuestoKey");

                    b.ToTable("Empleado", "DIM");
                });

            modelBuilder.Entity("HRM.SantaLucia.Web.Models.Entities.Nomina", b =>
                {
                    b.Property<int>("NominaKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NominaKey"));

                    b.Property<decimal>("Aguinaldo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Bonificaciones")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Comisiones")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DeduccionesQuincenales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DepartamentoKey")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadoKey")
                        .HasColumnType("int");

                    b.Property<decimal>("ExtrasQuincenales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Feriados")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HorasExtra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HorasTrabajadas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Miscelaneo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtrasDeducciones")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PagoHorasExtra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PagoHorasRegulares")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PeriodoKey")
                        .HasColumnType("int");

                    b.Property<int>("PuestoKey")
                        .HasColumnType("int");

                    b.Property<decimal>("QTYDiasFeriados")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("QTYHorasExtras")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("QTYHorasRegulares")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Renta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalarioBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalarioNeto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sede")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SeguroSocial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDeducciones")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalExtras")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("NominaKey");

                    b.HasIndex("DepartamentoKey");

                    b.HasIndex("EmpleadoKey");

                    b.HasIndex("PuestoKey");

                    b.ToTable("Nomina", "FACT");
                });

            modelBuilder.Entity("HRM.SantaLucia.Web.Models.Entities.Puesto", b =>
                {
                    b.Property<int>("PuestoKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PuestoKey"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombrePuesto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("SalarioMaximo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SalarioMinimo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoPuesto")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PuestoKey");

                    b.ToTable("Puesto", "DIM");
                });

            modelBuilder.Entity("HRM.SantaLucia.Web.Models.Entities.Rendimiento", b =>
                {
                    b.Property<int>("RendimientoKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RendimientoKey"));

                    b.Property<decimal>("CalificacionGeneral")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Comentarios")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("EmpleadoKey")
                        .HasColumnType("int");

                    b.Property<int>("EvaluadorKey")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("FechaKey")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("MetasAlcanzadas")
                        .HasColumnType("int");

                    b.Property<int>("MetasPropuestas")
                        .HasColumnType("int");

                    b.Property<string>("PeriodoEvaluacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RendimientoKey");

                    b.HasIndex("EmpleadoKey");

                    b.HasIndex("EvaluadorKey");

                    b.ToTable("Rendimiento", "FACT");
                });

            modelBuilder.Entity("HRM.SantaLucia.Web.Models.Entities.Vacaciones", b =>
                {
                    b.Property<int>("VacacionKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VacacionKey"));

                    b.Property<int?>("AprobadorKey")
                        .HasColumnType("int");

                    b.Property<int>("DiasSolicitados")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadoKey")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("FechaFinKey")
                        .HasColumnType("int");

                    b.Property<int>("FechaInicioKey")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VacacionKey");

                    b.HasIndex("AprobadorKey");

                    b.HasIndex("EmpleadoKey");

                    b.ToTable("Vacaciones", "FACT");
                });

            modelBuilder.Entity("HRM.SantaLucia.Web.Models.Entities.Asistencia", b =>
                {
                    b.HasOne("HRM.SantaLucia.Web.Models.Entities.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("HRM.SantaLucia.Web.Models.Entities.Departamento", b =>
                {
                    b.HasOne("HRM.SantaLucia.Web.Models.Entities.Departamento", "DepartamentoPadre")
                        .WithMany()
                        .HasForeignKey("DepartamentoPadreKey")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HRM.SantaLucia.Web.Models.Entities.Empleado", "Jefe")
                        .WithMany()
                        .HasForeignKey("JefeKey")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DepartamentoPadre");

                    b.Navigation("Jefe");
                });

            modelBuilder.Entity("HRM.SantaLucia.Web.Models.Entities.Empleado", b =>
                {
                    b.HasOne("HRM.SantaLucia.Web.Models.Entities.Banco", "Banco")
                        .WithMany()
                        .HasForeignKey("BancoKey")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HRM.SantaLucia.Web.Models.Entities.Departamento", "Departamento")
                        .WithMany("Empleados")
                        .HasForeignKey("DepartamentoKey")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HRM.SantaLucia.Web.Models.Entities.Puesto", "Puesto")
                        .WithMany("Empleados")
                        .HasForeignKey("PuestoKey")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Banco");

                    b.Navigation("Departamento");

                    b.Navigation("Puesto");
                });

            modelBuilder.Entity("HRM.SantaLucia.Web.Models.Entities.Nomina", b =>
                {
                    b.HasOne("HRM.SantaLucia.Web.Models.Entities.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRM.SantaLucia.Web.Models.Entities.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRM.SantaLucia.Web.Models.Entities.Puesto", "Puesto")
                        .WithMany()
                        .HasForeignKey("PuestoKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departamento");

                    b.Navigation("Empleado");

                    b.Navigation("Puesto");
                });

            modelBuilder.Entity("HRM.SantaLucia.Web.Models.Entities.Rendimiento", b =>
                {
                    b.HasOne("HRM.SantaLucia.Web.Models.Entities.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRM.SantaLucia.Web.Models.Entities.Empleado", "Evaluador")
                        .WithMany()
                        .HasForeignKey("EvaluadorKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Evaluador");
                });

            modelBuilder.Entity("HRM.SantaLucia.Web.Models.Entities.Vacaciones", b =>
                {
                    b.HasOne("HRM.SantaLucia.Web.Models.Entities.Empleado", "Aprobador")
                        .WithMany()
                        .HasForeignKey("AprobadorKey")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HRM.SantaLucia.Web.Models.Entities.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aprobador");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("HRM.SantaLucia.Web.Models.Entities.Departamento", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("HRM.SantaLucia.Web.Models.Entities.Puesto", b =>
                {
                    b.Navigation("Empleados");
                });
#pragma warning restore 612, 618
        }
    }
}
